language: csharp
dist: trusty
os:
  - linux
  - osx
osx_image: xcode7.1
mono:
  - 4.2.2
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
branches:
  only:
    - master
    - release
    - dev
    - /^ci-.*$/
env: KOREBUILD_TEST_SKIPMONO=1
before_install:
   - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install icu4c; fi
script:
  - ./build.sh verify
