language: csharp
dist: trusty
os:
  - linux
  # - osx CoreCLR does not support OS X 10.9 (yet)
mono:
  - beta
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
branches:
  only:
    - master
    - release
    - dev
    - /^(.*\/)?ci-.*$/
env: KOREBUILD_TEST_SKIPMONO=1
before_install:
  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install openssl; brew link --force openssl; fi
script:
  - ./build.sh --quiet verify
notifications:
  webhooks:
    secure: "a2AoARlYhgHFj7Jec1TbcqNPi3oJziHVaVPScFGiBezfJvXu3+6c9amMAzK3ZSN0lxaYyBhmkIM8eE73VxLJo9T2Y28L0dwKQi1xaVuLXUf2XLMFjdP99MHPsFA32gFJNqSdvVCF637qkopkjz0xyxsFjf2vDe7PvQFX54/sYkk="
  on_success: always
  on_failure: always
  on_start: always
