variables:
  - name: _BuildConfig
    value: Release
  - name: _TeamName
    value: AspNetCore
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: true

trigger:
  - master
  - release/*

pr: ['*']

jobs:
  - template: eng/common/templates/jobs/jobs.yml
    parameters:
      enableMicrobuild: true
      enablePublishBuildArtifacts: true
      enablePublishBuildAssets: true
      enablePublishTestResults: true
      enableTelemetry: true
      helixRepo: aspnet/EntityFrameworkCore
      jobs:
        - job: Windows
          pool:
            vmImage: win1803
          container:
            image: microsoft/mssql-server-windows-developer
            options: -e ACCEPT_EULA=Y -e SA_PASSWORD=Password12!
          variables:
            - Test__SqlServer__DefaultConnection: Data Source=(local);User ID=sa;Password=Password12!
            - Test__SqlServer__SupportsMemoryOptimized: true
            - Test__SqlServer__SupportsHiddenColumns: true
            - _InternalBuildArgs: ''
            - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
              - group: DotNet-Blob-Feed
              - _SignType: real
              - _PublishBlobFeedUrl: https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/index.json
              - _DotNetPublishToBlobFeed: true
              - _InternalBuildArgs: /p:DotNetSignType=$(_SignType) /p:TeamName=$(_TeamName) /p:DotNetPublishBlobFeedKey=$(dotnetfeed-storage-access-key-1) /p:DotNetPublishBlobFeedUrl=$(_PublishBlobFeedUrl) /p:DotNetPublishToBlobFeed=$(_DotNetPublishToBlobFeed) /p:OfficialBuildId=$(BUILD.BUILDNUMBER)
          steps:
            - script: "echo ##vso[build.addbuildtag]daily-build"
              condition: and(ne(variables['Build.Reason'], 'PullRequest'), ne(variables['IsFinalBuild'], 'true'))
              displayName: 'Set CI tags'
            - script: "echo ##vso[build.addbuildtag]release-candidate"
              condition: and(ne(variables['Build.Reason'], 'PullRequest'), eq(variables['IsFinalBuild'], 'true'))
              displayName: 'Set CI tags'
            - script: eng\common\cibuild.cmd -configuration $(_BuildConfig) -prepareMachine $(_InternalBuildArgs)
              name: Build
            - task: PublishBuildArtifacts@1
              displayName: Upload artifacts
              condition: eq(variables['system.pullrequest.isfork'], false)
              inputs:
                pathtoPublish: 'artifacts/packages/'
                artifactName: packages
                artifactType: Container
                parallel: true

        - job: macOS
          pool:
            vmImage: macOS-10.13
          steps:
            - bash: brew install libspatialite
              displayName: Install SpatiaLite
              continueOnError: true
            - script: eng/common/cibuild.sh --configuration $(_BuildConfig) --binaryLog --prepareMachine
              name: Build
              continueOnError: true

        - job: Linux
          pool:
            vmImage: ubuntu-16.04
          container:
            image: mcr.microsoft.com/mssql/server
            options: -e ACCEPT_EULA=Y -e SA_PASSWORD=Password12!
          variables:
            - Test__SqlServer__DefaultConnection: Data Source=127.0.0.1;User ID=sa;Password=Password12!
            - Test__SqlServer__SupportsMemoryOptimized: true
            - Test__SqlServer__SupportsHiddenColumns: true
          steps:
            - bash: apt-get install -y libsqlite3-mod-spatialite
              displayName: Install SpatiaLite
              continueOnError: true
            - script: eng/common/cibuild.sh --configuration $(_BuildConfig) --prepareMachine
              name: Build
