trigger:
  - master
  - release/*
  - feature/*
  - internal/release/3.*

#resources:
#  containers:
#    - container: cosmosEmulator
#      image: microsoft/azure-cosmosdb-emulator
#      ports:
#        - 8081:8081

jobs:
- job: Windows

  pool:
    vmImage: 'windows-latest'

#  services:
#    cosmosEmulator: cosmosEmulator

  steps:
  - task: Cache@2
    inputs:
      key: 'ConstantCosmosMsiKey'
      path: cosmosdb-emulator-cache-dir
      cacheHitVar: CACHE_RESTORED
    displayName: Cache Cosmos Emulator MSI
  - powershell: mkdir cosmosdb-emulator-cache-dir; Invoke-WebRequest https://aka.ms/cosmosdb-emulator -outfile cosmosdb-emulator-cache-dir\cosmosdb-emulator.msi
    condition: ne(variables.CACHE_RESTORED, 'true')
    displayName: Download CosmosDB Emulator
  - powershell: msiexec /i cosmosdb-emulator-cache-dir\cosmosdb-emulator.msi /qn /quiet /norestart /log install.log
    displayName: Install CosmosDB Emulator
  - powershell: |
      Import-Module "$env:ProgramFiles\Azure Cosmos DB Emulator\PSModules\Microsoft.Azure.CosmosDB.Emulator"
      Start-CosmosDbEmulator
    displayName: Start CosmosDB Emulator

  - script: restore.cmd
    displayName: Restore
  - script: .dotnet\dotnet.exe test test\EFCore.Cosmos.FunctionalTests