variables:
  - name: _BuildConfig
    value: Release
  - name: _TeamName
    value: AspNetCore
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: true

trigger:
  - master
  - release/*

pr: ['*']

jobs:
  - template: eng/common/templates/jobs/jobs.yml
    parameters:
      enableMicrobuild: true
      enablePublishBuildArtifacts: true
      enablePublishBuildAssets: true
      enablePublishTestResults: true
      enableTelemetry: true
      helixRepo: aspnet/EntityFrameworkCore
      jobs:
        - job: Windows
          # HACK: Work around dotnet/arcade#1175
          ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
            timeoutInMinutes: 0
          pool:
            ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
              name: dotnet-internal-temp
            ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
              name: dotnet-external-temp
          variables:
            - _InternalBuildArgs: ''
            - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
              - group: DotNet-Blob-Feed
              - _SignType: real
              - _PublishBlobFeedUrl: https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/index.json
              - _DotNetPublishToBlobFeed: true
              - _InternalBuildArgs: /p:DotNetSignType=$(_SignType) /p:TeamName=$(_TeamName) /p:DotNetPublishBlobFeedKey=$(dotnetfeed-storage-access-key-1) /p:DotNetPublishBlobFeedUrl=$(_PublishBlobFeedUrl) /p:DotNetPublishToBlobFeed=$(_DotNetPublishToBlobFeed) /p:OfficialBuildId=$(BUILD.BUILDNUMBER)
          steps:
            - powershell: |
                SqlLocalDB stop MSSQLLocalDB -i
                SqlLocalDB start MSSQLLocalDB
                & "$env:ProgramFiles\Microsoft SQL Server\110\Tools\Binn\SQLCMD.EXE" -S '(localdb)\MSSQLLocalDB' -b -Q @'
                  DECLARE @name nvarchar(255);
                  DECLARE db CURSOR FOR SELECT Name FROM sysdatabases WHERE Name NOT IN ('master', 'tempdb', 'model', 'msdb');
                  OPEN db;
                  FETCH NEXT FROM db INTO @name;
                  WHILE @@FETCH_STATUS = 0
                  BEGIN
                    SET @name = REPLACE(@name, ']', ']]');
                    PRINT 'Dropping database [' + @name + ']';
                    SET @name = 'DROP DATABASE [' + @name + ']';
                    EXEC (@name);
                    FETCH NEXT FROM db INTO @name;
                  END;
                  CLOSE db;
                  DEALLOCATE db;
                '@
              displayName: Cleanup databases
            - script: eng\common\cibuild.cmd -configuration $(_BuildConfig) -prepareMachine $(_InternalBuildArgs)
              name: Build
            # Detect OSS Components in use in the product. Only needs to run on one OS in the matrix.
            - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
              displayName: Detect components
              condition: and(succeeded(), eq(variables['system.pullrequest.isfork'], false))
            - task: PublishBuildArtifacts@1
              displayName: Upload artifacts
              condition: eq(variables['system.pullrequest.isfork'], false)
              inputs:
                pathtoPublish: 'artifacts/packages/'
                artifactName: packages
                artifactType: Container
                parallel: true

        - job: macOS
          pool:
            ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
              name: Hosted Mac Internal
            ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
              name: Hosted macOS
          steps:
            - bash: brew install libspatialite
              displayName: Install SpatiaLite
              continueOnError: true
            - script: eng/common/cibuild.sh --configuration $(_BuildConfig) --prepareMachine
              name: Build

        - job: Linux
          pool: Hosted Ubuntu 1604
          steps:
            - bash: sudo apt-get install -y libsqlite3-mod-spatialite
              displayName: Install SpatiaLite
              continueOnError: true
            - script: eng/common/cibuild.sh --configuration $(_BuildConfig) --prepareMachine
              name: Build
