trigger:
- master
- release/*

# See https://github.com/aspnet/BuildTools
resources:
  repositories:
  - repository: buildtools
    type: github
    endpoint: DotNet-Bot GitHub Connection
    name: aspnet/BuildTools
    ref: refs/heads/release/2.2

phases:
- template: .vsts-pipelines/templates/project-ci.yml@buildtools
  parameters:
    agentOs: macOS
    beforeBuild:
    - bash: brew install libspatialite
      displayName: Install SpatiaLite

phases:
- template: .vsts-pipelines/templates/project-ci.yml@buildtools
  parameters:
    agentOs: Linux
    beforeBuild:
    - bash: sudo apt-get install -y libsqlite3-mod-spatialite
      displayName: Install SpatiaLite
